site_name: GILVAN MOURA | FULL STACK DEVELOPER
nav:
    - Início: index.md
    - "Perfil / contato": sobre-mim.md
    - "Histórico profissional" : historico.md
    - "Formação acadêmica": formacao.md
    - Skills: skills.md
    - CV em PDF: pdf.md
#theme: material
theme:
    name: material
    language: pt-BR
    logo: ./imagens/resumo.png
    favicon: ./imagens/resumo.png
language: pt
extra_javascript:
    - 'require.js'
    - 'custom.js'
    - 'resumo.js'
    - 'skills.js'
    - 'https://vlibras.gov.br/app/vlibras-plugin.js'
    - 'vlibras.js'
extra_css:
    - 'custom.css' 
    - 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
    - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css