site_name: GILVAN MOURA
nav:
    - Início: index.md
    - "Sobre / contato": sobre-mim.md
    - "Histórico profissional" : historico.md
    - "Formação acadêmica": formacao.md
    - Skills: skills.md
    - CV em PDF: "/cv.pdf"
theme: material
language: pt
extra_javascript:
    - 'require.js'
    - 'custom.js'
extra_css:
    - 'custom.css' 
    - 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css'
    - https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css